### ISSUE TITLE
RuntimeError: espeak not installed on your system

### ISSUE THREAD

**Issue by PasaOpasen** [bootphon/phonemizer#44]
How to solve `RuntimeError: espeak not installed on your system` on Windows without using Linux in Windows?

**Comment by mmmaat** [comment]
You need to install espeak, or better, espeak-ng : https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md#windows

**Comment by PasaOpasen** [comment]
Yes, I did it and can open and use espeak application, but phonemizer raises that error still

**Comment by mmmaat** [comment]
Ok, so I suppose espeak-ng is not in your PATH. But phonemizer provides an alternative way to specify the path to espeak: you can setup the environment variable `PHONEMIZER_ESPEAK_PATH` with the absolute path to espeak (see https://github.com/bootphon/phonemizer/blob/master/phonemizer/backend/espeak.py#L62).

**Comment by PasaOpasen** [comment]
The path to espeak if the path to folder with TTSApp.exe, sure?

**Comment by mmmaat** [comment]
I don't have Windows so I cannot really help you with hands on... It has already been used on Windows and you are the first one to report such an issue. The `PHONEMIZER_ESPEAK_PATH` must be an absolute path to the `.exe` file, along with the `.exe` extension.

Maybe `PHONEMIZER_ESPEAK_PATH=C:\Program Files (x86)\eSpeak.exe` will work? If you have such a file... The good file must be an executable one, usable from command line (not a GUI one).

You can also try this one: http://sourceforge.net/projects/espeak/files/espeak/espeak-1.48/setup_espeak-1.48.04.exe

**Comment by PasaOpasen** [comment]
Very good! There was the file C:\Program Files (x86)\eSpeak\command_line\espeak.exe and I did assign it to PHONEMIZER_ESPEAK_PATH. Now it works!

**Comment by sujithvoona** [comment]
Hey @PasaOpasen, before setting the environment variable path as PHONEMIZER_ESPEAK_PATH = C:\Program Files (x86)\eSpeak\command_line\espeak.exe did you store espeak.py file at any specific place.

Did the error got cleared after placing this espeak.py at a certain place and you set the environment variable path or you had nothing to do with the espeak.py file and set the environment variable "PHONEMIZER_ESPEAK_PATH"

I created a new environment variable PHONEMIZER_ESPEAK_PATH and I gave the path same as you C:\Program Files (x86)\eSpeak\command_line\espeak.exe did you store espeak.py. I am still facing the error. 

Please help.

**Comment by danthemango** [comment]
That's because you're trying to add the path to the .exe file, you need to add the directory instead to the PATH variable:
"C:\Program Files (x86)\eSpeak\command_line"

**Comment by richardfoltin** [comment]
The variable name is changed to PHONEMIZER_ESPEAK_LIBRARY and it refers to the .dll now:
PHONEMIZER_ESPEAK_LIBRARY="c:\Program Files\eSpeak NG\libespeak-ng.dll"

**Comment by cantabile-kwok** [comment]
> The variable name is changed to PHONEMIZER_ESPEAK_LIBRARY and it refers to the .dll now: PHONEMIZER_ESPEAK_LIBRARY="c:\Program Files\eSpeak NG\libespeak-ng.dll"

This worked very well and saved me a headache, thanks!

**Comment by wukongsleeping** [comment]
注意是PHONEMIZER_ESPEAK_LIBRARY和PHONEMIZER_ESPEAK_PATH 
1.PHONEMIZER_ESPEAK_LIBRARY="c:\Program Files\eSpeak NG\libespeak-ng.dll"
2.PHONEMIZER_ESPEAK_PATH =“c:\Program Files\eSpeak NG”

**Comment by TheKOG** [comment]
> 注意是PHONEMIZER_ESPEAK_LIBRARY和PHONEMIZER_ESPEAK_PATH 1.PHONEMIZER_ESPEAK_LIBRARY="c:\Program Files\eSpeak NG\libespeak-ng.dll" 2.PHONEMIZER_ESPEAK_PATH =“c:\Program Files\eSpeak NG”

finally it works!

**Comment by anushvst** [comment]
1.PHONEMIZER_ESPEAK_LIBRARY  =  C:\Program Files\eSpeak NG\libespeak-ng.dll
2.PHONEMIZER_ESPEAK_PATH  =  C:\Program Files\eSpeak NG

add these variables to your system variables in environment variables
it will work

**Comment by mmmaat** [comment]
Hi, I'm not a Windows expert so I can't really help you... But. Are you sure the "C:\Program Files\eSpeak NG\libespeak-ng.dll" you provided actually is an existing file?

Another solution: Use the docker image: https://bootphon.github.io/phonemizer/install.html#docker-image. Install docker on your machine, then install the docker image of the phonemizer.

Another solution: Use Windows subsystem for Linux (https://learn.microsoft.com/en-us/windows/wsl/install)

**Comment by djpelu** [comment]
thanks for the fast answer, the file actually exists, but it is in Program Files (x86) so i changed the path. However it doesn't come up when i look for it as a directory, could this be the problem? thanks, i'm really not an expert

**Comment by mmmaat** [comment]
Ok... so it **MUST BE** the exact and absolute path to the `libespeak-ng.dll` file you installed with eSpeakNG. For instance `C:\Program Files (x86)\eSpeak NG\libespeak-ng.dll` or whatever it is on your computer. Add that path to the `PHONEMIZER_ESPEAK_LIBRARY` environment variable (I don't know how to do it on Windows) and it should work.

**Comment by djpelu** [comment]
i checked many times and the path is correct, however it's still not working. thank you again for your help, hope i can find a solution and post it here for anyone that may need it

**Comment by djpelu** [comment]
![tt](https://user-images.githubusercontent.com/116528023/197594875-cef3e663-6e7d-4547-973e-35750170dd09.png)

this is what i've done, if someone knows how to make this work on windows, thank you!

**Comment by QuLiao1117** [comment]
> 
Did you solve that problem now? I meet the same problem with you.

**Comment by Skye-ZHAO** [comment]
Me too! Please let me know if this problem solved. Thanks!

**Comment by djpelu** [comment]
Unfortunately I couln’t find a solution and i had to resort to another package

**Comment by LingXuanYin** [comment]
Hey ,I've solved this ！

(1) Install espeak 
with cmd command 
`winget install espeak` 
or download exe and install :[https://sourceforge.net/projects/espeak/files/espeak/espeak-1.48/setup_espeak-1.48.04.exe/download](url)

(2) Install espeak-ng
 [https://github.com/espeak-ng/espeak-ng/releases](url)

(3) Copy the espeak-ng's dll `C:\Program Files\eSpeak NG\libespeak-ng.dll` to `C:\Program Files (x86)\eSpeak\command_line` and rename it to `espeak-ng.dll` or `espeak.dll`

(4) Add `C:\Program Files (x86)\eSpeak\command_line`  to environment variable `Path`

(5) Restart your vscode/cmd/Jupyter or anything you run VITS

You can uninstall eSpeak NG after you've done this

**Comment by mmmaat** [comment]
FYI we have a working workflow of installing espeak with phonemizer on Windows within our github actions: https://github.com/bootphon/phonemizer/blob/master/.github/workflows/windows.yaml

Basically on PowerShell you have to do:
```powershell
# Install espeak-ng-1.50
$source = 'https://github.com/espeak-ng/espeak-ng/releases/download/1.50/espeak-ng-20191129-b702b03-x64.msi'
Invoke-WebRequest -Uri $source -OutFile espeak.msi
Start-Process msiexec.exe -Wait -ArgumentList '/I espeak.msi /qn'

# Set the environment variable with the espeak-ng DLL (I'm not sure of that, took from [1] but didn't tested)
[Environment]::SetEnvironmentVariable('PHONEMIZER_ESPEAK_LIBRARY', 'C:\\Program Files\eSpeak NG\libespeak-ng.dll', 'Machine')

# Finally install phonemizer
python setup.py install
phonemizer --version
```

Can someone on Windows can test it? Hope this helps...

-----------

[1] https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.2#saving-environment-variables-with-setenvironmentvariable

**Comment by GUJISONG** [comment]
In Anaconda environment, install espeak-ng then
`conda env config vars set PHONEMIZER_ESPEAK_PATH=“C:\Program Files\eSpeak NG”`
`conda env config vars set PHONEMIZER_ESPEAK_LIBRARY="C:\Program Files\eSpeak NG\libespeak-ng.dll"`
It just worked.

**Comment by Cmaury** [comment]
I was able to root cause this issue, at least for myself and on windows.
I was getting the same error, and it turns out there was a mismatch between my path system, which is 64bit and my espeak instal which was 32bit. My espeak and espeak NG installs were x86 but running:

'python -c "import platform; print(platform.architecture())"'

if you update espeak NG to match your system (64bit and 64bit) it should work and find the library once you've updated your environment variables. 

I only found this by commenting our the initial error, and getting a more detailed error message when it failed further downstream.

**Comment by corvusMidnight** [comment]
> I was able to root cause this issue, at least for myself and on windows. I was getting the same error, and it turns out there was a mismatch between my python system, which is 64bit and my espeak instal which was 32bit. My espeak and espeak NG installs were x86 but running:
> 
> 'python -c "import platform; print(platform.architecture())"'
> 
> if you update espeak NG to match your system (64bit and 64bit) it should work and find the library once you've updated your environment variables.
> 
> I only found this by commenting our the initial error, and getting a more detailed error message when it failed further downstream.

There must be some issues with Windows 10 x64bit ([see here](https://github.com/espeak-ng/espeak-ng/issues/966#issue-920475954)). How did you install the 64bit version of espeak?

**Comment by younengma** [comment]
Editting the file `C:\ProgramData\Anaconda3\Lib\site-packages\phonemizer\backend\espeak.py`  works fine. 
I tried to add environment variables, it doesn't work.  directly return the absolutely path in the following function works for me.
phonemizer version is 2.2.1.

    def espeak_path():
        """Returns the absolute path to the espeak executable"""
        # just return the espeak path 
        return  r"C:\Program Files\eSpeak NG\espeak-ng.exe"
        if 'PHONEMIZER_ESPEAK_PATH' in os.environ:
            espeak = os.environ['PHONEMIZER_ESPEAK_PATH']
            if not (os.path.isfile(espeak) and os.access(espeak, os.X_OK)):
                raise ValueError(
                    f'PHONEMIZER_ESPEAK_PATH={espeak} '
                    f'is not an executable file')
            return os.path.abspath(espeak)

**Comment by ziyaad30** [comment]
Better method

```
from phonemizer.backend.espeak.wrapper import EspeakWrapper
_ESPEAK_LIBRARY = 'C:\Program Files\eSpeak NG\libespeak-ng.dll'
EspeakWrapper.set_library(_ESPEAK_LIBRARY)
```

**Comment by Artrajz** [comment]
> Better method
> 
> ```
> from phonemizer.backend.espeak.wrapper import EspeakWrapper
> _ESPEAK_LIBRARY = 'C:\Program Files\eSpeak NG\libespeak-ng.dll'
> EspeakWrapper.set_library(_ESPEAK_LIBRARY)
> ```

It indeed works!

**Comment by nehc0** [comment]
> Better method
> 
> ```
> from phonemizer.backend.espeak.wrapper import EspeakWrapper
> _ESPEAK_LIBRARY = 'C:\Program Files\eSpeak NG\libespeak-ng.dll'
> EspeakWrapper.set_library(_ESPEAK_LIBRARY)
> ```

Thank you very much!

**Comment by RomanVD39** [comment]
from phonemizer.backend.espeak.wrapper import EspeakWrapper
print(EspeakWrapper.library())
->C:\Program Files (x86)\eSpeak NG\libespeak-ng.dll

But when use phonemize():
... ... ...
File "D:\PyProjects\LV\venv\Lib\site-packages\phonemizer\backend\base.py", line 77, in __init__
    raise RuntimeError(  # pragma: nocover
RuntimeError: espeak not installed on your system

Any help?

**Comment by RomanVD39** [comment]
I have uninstalled
[espeak-ng-X86.msi](https://github.com/espeak-ng/espeak-ng/releases/download/1.51/espeak-ng-X86.msi)
then installed
[espeak-ng-X64.msi](https://github.com/espeak-ng/espeak-ng/releases/download/1.51/espeak-ng-X64.msi)

So, C:\Program Files (x86)\eSpeak NG\libespeak-ng.dll was changed to C:\Program Files (x86)\eSpeak NG\libespeak-ng.dll

And this
>from phonemizer.backend.espeak.wrapper import EspeakWrapper
>_ESPEAK_LIBRARY = 'C:\Program Files\eSpeak NG\libespeak-ng.dll'
>EspeakWrapper.set_library(_ESPEAK_LIBRARY)
works fine!

Be carefull for right msi version!

**Comment by Kkordik** [comment]
Guys, nothing worked for me from here, so I asked bing chat.

bing answer:
“Reboot the system: Sometimes changes in environment variables do not take effect until the system is rebooted.”

Finally worked. I've wasted 2 hours on this.

**Comment by BarathwajAnandan** [comment]
for linux or WSL users, Instead of doing pip install espeak, try 'sudo apt-get install espeak-ng' 
worked for me.

**Comment by audiocommander** [comment]
fyi, I'm not on Windows, but on Mac OS Sonoma (ARM64, M2) and I have exactly the same troubles, hours sinking into this install. I have installed espeak via brew, it's available on zsh, I can open it and synthesise speech. I tried installed espeak-ng via pip (failed), via brew (kinda worked), via ports (worked) and made sure that I exported all paths correctly as seen here and otherwhere. 

So, on shell, I have espeak, on python shell I can access espeakng, seems all good. But Juypter still tells me I haven't installed espeak. So I guess, this is rather an issue of how this library accesses espeak. I admit, I don't understand, why we need to handle full paths to dynamic libs when the full program command is available on my shell and thus also in python; isn't this the point of having conda and pip and such?

Trying a reboot now as a last step before giving up...

**Comment by mrticker** [comment]
I've had this problem on Windows 10. The issue is in the following piece of code in `...\site-packages\phonemizer\backend\espeak\wrapper.py`, in function `library()`:

`		if 'PHONEMIZER_ESPEAK_LIBRARY' in os.environ:
			library = pathlib.Path(os.environ['PHONEMIZER_ESPEAK_LIBRARY'])
			if not (library.is_file() and os.access(library, os.R_OK)):
				raise RuntimeError(  # pragma: nocover
					f'PHONEMIZER_ESPEAK_LIBRARY={library} '
					f'is not a readable file')`

If you've added PHONEMIZER_ESPEAK_LIBRARY as a path with backslashes, it will fail. If you use forward slashes, it will work.

PHONEMIZER_ESPEAK_LIBRARY=C:/Program Files/eSpeak NG/libespeak-ng.dll

So, 
1. download easpeak-ng from https://github.com/espeak-ng/espeak-ng/releases/
2. install it
3. add PHONEMIZER_ESPEAK_LIBRARY to environment variables, but with forward slashes.

**Comment by cmp-nct** [comment]
Took me 2 hours to get espeak working with phonemizer.
That issue should not have been closed without implementing the needed changes so people do not have to waste so much time.
That should be bold information in the readme on the frontpage

**Comment by sunnnnnnnny** [comment]
@audiocommander  For macos, if use `brew install espeak`; it only need change some code of ctypes package that find  `find_library` function; Especially,  edit miniconda3/envs/env/lib/pythonx/ctypes/util.py  file with `find_library` function‘s  `possible` variable(actually espeak lib path is `/opt/homebrew/lib`), it works for me;

**Comment by mmmaat** [comment]
@sunnnnnnnny this is usually a bad idea to edit files from the standard library... Instead you may want to set the environment variable `PHONEMIER_ESPEAK_LIBRARY=/opt/homebrew/lib/espeak.dylib` (or the actual path to the espeak library on your machine). Or you can use/adapt this Python snippet:
```python
from phonemizer.backend.espeak.wrapper import EspeakWrapper
_ESPEAK_LIBRARY = 'C:\Program Files\eSpeak NG\libespeak-ng.dll'
EspeakWrapper.set_library(_ESPEAK_LIBRARY)
```

**Comment by sunnnnnnnny** [comment]
> @sunnnnnnnny this is usually a bad idea to edit files from the standard library... Instead you may want to set the environment variable `PHONEMIER_ESPEAK_LIBRARY=/opt/homebrew/lib/espeak.dylib` (or the actual path to the espeak library on your machine). Or you can use/adapt this Python snippet:
> 
> ```python
> from phonemizer.backend.espeak.wrapper import EspeakWrapper
> _ESPEAK_LIBRARY = 'C:\Program Files\eSpeak NG\libespeak-ng.dll'
> EspeakWrapper.set_library(_ESPEAK_LIBRARY)
> ```

ok,thanks; i see it;

**Comment by mmmaat** [comment]
Ok... This issue seems to cause a lot of troubles since a long time... I just updated the Windows installation instructions (https://bootphon.github.io/phonemizer/install.html#on-windows). Hope this helps.

I do not use - and don't know much about -  Windows or MacOS so it's difficult for me to help or replicate problems from this thread.

Anyway I welcome any PR with improvement on the documentation from Windows/macOs users :1st_place_medal:, thank you!

**Comment by cmp-nct** [comment]
> Ok... This issue seems to cause a lot of troubles since a long time... I just updated the Windows installation instructions (https://bootphon.github.io/phonemizer/install.html#on-windows). Hope this helps.
> 
> I do not use - and don't know much about - Windows or MacOS so it's difficult for me to help or replicate problems from this thread.
> 
> Anyway I welcome any PR with improvement on the documentation from Windows/macOs users 🥇, thank you!

Add this to the instructions:
conda env config vars set PHONEMIZER_ESPEAK_PATH=“C:\Program Files\eSpeak NG”
conda env config vars set PHONEMIZER_ESPEAK_LIBRARY="C:\Program Files\eSpeak NG\libespeak-ng.dll"

I've tried a ton of things, including renaming the library (removing lib from libespeak-ng.dll removed 50% of the errors but then it got stuck again) or copying it into system32, nothing worked to get through the "layers of detection", those two environment variables did it.

**Comment by teddybear082** [comment]
> In Anaconda environment, install espeak-ng then `conda env config vars set PHONEMIZER_ESPEAK_PATH=“C:\Program Files\eSpeak NG”` `conda env config vars set PHONEMIZER_ESPEAK_LIBRARY="C:\Program Files\eSpeak NG\libespeak-ng.dll"` It just worked.

THANK YOU SO MUCH.  I spent over an hour this morning trying to get espeak phonemizer, which is a depency of styletts2, working on my system with anaconda, and your solution finally solved it

**Comment by iackov** [comment]
My Solution for Windows:

from phonemizer.backend.espeak.wrapper import EspeakWrapper
EspeakWrapper.set_library('C:\Program Files\eSpeak NG\libespeak-ng.dll')

eSpeak NG - Installed from official site (msi)

**Comment by jthack** [comment]
this is what works on my mac:
export PHONEMIZER_ESPEAK_LIBRARY=/opt/homebrew/lib/libespeak-ng.dylib

**Comment by MonolithFoundation** [comment]
I didn't get it, forabout 200 years, why phonemizer founding espeak lib can't found more wisely?
If uses need to do it over and over again, why not wisely choose it inside phonemizer? @bootphon

**Comment by karolina-sowinska** [comment]
If you installed espeak with homebrew, set these in the PATH:

export PHONEMIZER_ESPEAK_LIBRARY=/opt/homebrew/lib/libespeak-ng.dylib
export PHONEMIZER_ESPEAK_PATH=/opt/homebrew/bin

**Comment by thewh1teagle** [comment]
Once this PR merged:

- https://github.com/bootphon/phonemizer/pull/191

It will be possible to use [espeakng-loader](https://github.com/thewh1teagle/espeakng-loader?tab=readme-ov-file#usage-with-phonemizer) with no need to install espeak-ng system wide!

Meanwhile if you want you can use along with [phonemizer-fork](https://pypi.org/project/phonemizer-fork) which has the merged PR

**Comment by bfrisco-raft** [comment]
> Once this PR merged:
> 
> * [feat: add option to use custom espeak data path #191](https://github.com/bootphon/phonemizer/pull/191)
> 
> It will be possible to use [espeakng-loader](https://github.com/thewh1teagle/espeakng-loader?tab=readme-ov-file#usage-with-phonemizer) with no need to install espeak-ng system wide!
> 
> Meanwhile if you want you can use along with [phonemizer-fork](https://pypi.org/project/phonemizer-fork) which has the merged PR

~~Will this still require espeak to query the Audio Card?~~

Nevermind, I fixed that, the wrong bit is being triggered for the espeak init. I will put a PR in for that as well, however I think The owner no longer works on the project.

**Comment by ramzeez88** [comment]
> Nothing works. The same issue on fresh win 10 and pip installation. "RuntimeError: espeak not installed on your system"

after installing espeak-ng.msi from https://github.com/espeak-ng/espeak-ng/releases
in kokoro.py add right after all the imports :
os.environ["PHONEMIZER_ESPEAK_LIBRARY"] = r"C:\Program Files\eSpeak NG\libespeak-ng.dll"
os.environ["PHONEMIZER_ESPEAK_PATH"] = r"C:\Program Files\eSpeak NG\espeak-ng.exe"
This works for me on Windows 11

**Comment by DaynerKurdi** [comment]
Hello, I seem to have problems linking phonemizer with espeak on Windows 11,  

Got espeak installed (1.52-dev), and got it working, 

I added the system environment variables to my system.

PHONEMIZER_ESPEAK_PATH= C:\Program Files (x86)\eSpeak NG
PHONEMIZER_ESPEAK_LIBRARY= C:\Program Files (x86)\eSpeak NG\libespeak-ng.dll

Sadly, phonemizer still does not detect and keeps getting this error.
Fatal error: espeak not installed on your system.

Which odd. 

I installed espeak on my local machine via .msi and tested it out with cmd.

**Comment by carlos-chourio** [comment]
> Hello, I seem to have problems linking phonemizer with espeak on Windows 11,
> 
> Got espeak installed (1.52-dev), and got it working,
> 
> I added the system environment variables to my system.
> 
> PHONEMIZER_ESPEAK_PATH= C:\Program Files (x86)\eSpeak NG PHONEMIZER_ESPEAK_LIBRARY= C:\Program Files (x86)\eSpeak NG\libespeak-ng.dll
> 
> Sadly, phonemizer still does not detect and keeps getting this error. Fatal error: espeak not installed on your system.
> 
> Which odd.
> 
> I installed espeak on my local machine via .msi and tested it out with cmd.

I think you needed to do:

PHONEMIZER_ESPEAK_LIBRARY= C:\Program Files\eSpeak NG\libespeak-ng.dll without the x86

**Comment by StephanAkkerman** [comment]
Can confirm that the following works for me on Windows 11:
```python
import os

from phonemizer import phonemize

os.environ["PHONEMIZER_ESPEAK_LIBRARY"] = "C:\Program Files\eSpeak NG\libespeak-ng.dll"

text = "chat"
# backend='espeak' is standaard
ipa = phonemize(text, language="fr-fr", backend="espeak", strip=True)
print(ipa)  # Output: ʃa
```

**Comment by PeppyMeow** [comment]
for windows user， visit 
https://github.com/espeak-ng/espeak-ng/releases/
and download the latest [espeak-ng.msi]
(https://github.com/espeak-ng/espeak-ng/releases/download/1.52.0/espeak-ng.msi)

after that，open power shell with admin right，and execute these four commands：

$env:PHONEMIZER_ESPEAK_LIBRARY = "c:\Program Files\eSpeak NG\libespeak-ng.dll"
$env:PHONEMIZER_ESPEAK_PATH = "c:\Program Files\eSpeak NG"
setx PHONEMIZER_ESPEAK_LIBRARY "c:\Program Files\eSpeak NG\libespeak-ng.dll"
setx PHONEMIZER_ESPEAK_PATH "c:\Program Files\eSpeak NG"


it works for me.
